package hr.model.vo;

import hr.model.eo.RegionsImpl;

import java.math.BigDecimal;

import oracle.jbo.RowIterator;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 30 10:26:07 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionsViewRowImpl extends ViewRowImpl {
    public static final int ENTITY_REGIONS = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        RegionId,
        RegionName,
        CountriesView;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int REGIONID = AttributesEnum.RegionId.index();
    public static final int REGIONNAME = AttributesEnum.RegionName.index();
    public static final int COUNTRIESVIEW = AttributesEnum.CountriesView.index();

    /**
     * This is the default constructor (do not remove).
     */
    public RegionsViewRowImpl() {
    }

    /**
     * Gets Regions entity object.
     * @return the Regions
     */
    public RegionsImpl getRegions() {
        return (RegionsImpl) getEntity(ENTITY_REGIONS);
    }

    /**
     * Gets the attribute value for REGION_ID using the alias name RegionId.
     * @return the REGION_ID
     */
    public BigDecimal getRegionId() {
        return (BigDecimal) getAttributeInternal(REGIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_ID using the alias name RegionId.
     * @param value value to set the REGION_ID
     */
    public void setRegionId(BigDecimal value) {
        setAttributeInternal(REGIONID, value);
    }

    /**
     * Gets the attribute value for REGION_NAME using the alias name RegionName.
     * @return the REGION_NAME
     */
    public String getRegionName() {
        return (String) getAttributeInternal(REGIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for REGION_NAME using the alias name RegionName.
     * @param value value to set the REGION_NAME
     */
    public void setRegionName(String value) {
        setAttributeInternal(REGIONNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link CountriesView.
     */
    public RowIterator getCountriesView() {
        return (RowIterator) getAttributeInternal(COUNTRIESVIEW);
    }
}

