package hr.model.vo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 30 10:26:07 EET 2019
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RegionsViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RegionsViewImpl() {
    }
}

