package hr.model.vo.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Dec 30 11:09:35 EET 2019
// ---------------------------------------------------------------------
public interface DepartmentsViewRow extends Row {
    void raiseSalary(double amount);
}

